
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujlwuvkrxlvoswwkerdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqbHd1dmtyeGx2b3N3d2tlcmRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3ODM1MDYsImV4cCI6MjA1NzM1OTUwNn0.htwJHr4Z4NlMZYVrH1nNGkU53DyBTWgMeOeUONYFy_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: typeof window !== 'undefined' ? localStorage : undefined,
  }
});

// Log initialization for debugging
console.log('Supabase client initialized with auth configuration:', {
  persistSession: true,
  autoRefreshToken: true,
  detectSessionInUrl: true,
  storage: 'localStorage',
});

// Create the videos bucket if it doesn't exist yet
export const ensureVideoBucket = async () => {
  try {
    const { data: buckets } = await supabase.storage.listBuckets();
    const videoBucket = buckets?.find(bucket => bucket.name === 'videos');
    
    if (!videoBucket) {
      console.log('Creating videos bucket in Supabase Storage...');
      const { data, error } = await supabase.storage.createBucket('videos', {
        public: true,
        fileSizeLimit: 100 * 1024 * 1024, // 100MB limit
      });
      
      if (error) {
        console.error('Error creating videos bucket:', error);
      } else {
        console.log('Videos bucket created successfully');
      }
    } else {
      console.log('Videos bucket already exists');
    }
  } catch (error) {
    console.error('Error ensuring videos bucket exists:', error);
  }
};

// Call this function to ensure the bucket exists (during app initialization)
if (typeof window !== 'undefined') {
  ensureVideoBucket().catch(console.error);
}
